name: CopsAndCrims
version: 1.5
author: MoKunz
main: com.talesdev.copsandcrims.CopsAndCrims
depend: [TalesCore,ProtocolLib]
commands:
    cvc:
      description: "§eMain command of this plugin"
      usage: "§e/cvc help"
      permission: cvc.command.cvc;
      permission-message: "§cYou don't have permission"
    cvcarena:
      description: "§eCvC commands for arena management"
      usage: "§e/cvcarena help"
      permission: cvc.command.cvcarena;
      permission-message: "§cYou don't have permission"